package generator

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/d1vbyz3r0/typed/common/typing"
	"github.com/stretchr/testify/require"
)

func TestGenerator_execTemplateNonMainPackage(t *testing.T) {
	outputPath := filepath.Join(t.TempDir(), "spec.go")
	g := &Generator{
		cfg: Config{
			Output: OutputConfig{
				Path:        outputPath,
				PackageName: "generated",
			},
		},
	}
	imports, err := createImportMappings(nil, initialMapping())
	require.NoError(t, err)

	require.NoError(t, g.execTemplate(imports, nil))

	src, err := os.ReadFile(outputPath)
	require.NoError(t, err)
	generated := string(src)
	require.True(t, strings.HasPrefix(generated, "// Code generated by typed. DO NOT EDIT\npackage generated\n"))
	require.Contains(t, generated, "var registry = typed.MustNewRegistry(")
	require.Contains(t, generated, "var spec = &openapi3.T{")
	require.NotContains(t, generated, "func main()")
	require.NotContains(t, generated, "CollectRoutes")
	require.NotContains(t, generated, "SaveSpec")
}

func TestGenerator_filterModels(t *testing.T) {
	root := makeTestModule(t)
	tests := []struct {
		name   string
		models []*typing.Type
		cfg    Config
		want   []string
	}{
		{
			name: "no filters keeps models from configured recursive root",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto", "DeprecatedUser"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
				typing.Named("example.com/project/internal/dto/auth/internal", "InternalToken"),
				typing.Named("example.com/project/internal/admin", "Admin"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.DeprecatedUser",
				"example.com/project/internal/dto.User",
				"example.com/project/internal/dto/auth.LoginRequest",
				"example.com/project/internal/dto/auth.LoginResponse",
				"example.com/project/internal/dto/auth/internal.InternalToken",
				"example.com/project/internal/admin.Admin",
			},
		},
		{
			name: "include by model name",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Name: "Response$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto/auth.LoginResponse",
			},
		},
		{
			name: "exclude by model name",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto", "DeprecatedUser"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							ExcludeModels: []ModelFilter{
								{Name: "^Deprecated"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.User",
				"example.com/project/internal/dto/auth.LoginRequest",
			},
		},
		{
			name: "exclude has priority over include",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
				typing.Named("example.com/project/internal/dto/auth/internal", "InternalToken"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Path: "^auth"},
							},
							ExcludeModels: []ModelFilter{
								{Name: "Response$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto/auth.LoginRequest",
				"example.com/project/internal/dto/auth/internal.InternalToken",
			},
		},
		{
			name: "include by relative package path",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
				typing.Named("example.com/project/internal/dto/auth/internal", "InternalToken"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Path: "^auth$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto/auth.LoginRequest",
				"example.com/project/internal/dto/auth.LoginResponse",
			},
		},
		{
			name: "exclude nested relative package path",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth/internal", "InternalToken"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							ExcludeModels: []ModelFilter{
								{Path: "^auth/internal$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.User",
				"example.com/project/internal/dto/auth.LoginRequest",
			},
		},
		{
			name: "include by full import path",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/user", "UserProfile"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{ImportPath: `/auth$`},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto/auth.LoginRequest",
			},
		},
		{
			name: "include by package name",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/user", "UserProfile"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Pkg: "^auth$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto/auth.LoginRequest",
			},
		},
		{
			name: "overlapping roots do not duplicate models",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
						},
						{
							Path:      filepath.Join(root, "internal", "dto", "auth"),
							Recursive: false,
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.User",
				"example.com/project/internal/dto/auth.LoginRequest",
				"example.com/project/internal/dto/auth.LoginResponse",
			},
		},
		{
			name: "include with AND: name and pkg both must match",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
				typing.Named("example.com/project/internal/dto/user", "LoginRequest"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Name: "^LoginRequest$", Pkg: "^auth$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto/auth.LoginRequest",
			},
		},
		{
			name: "exclude multiple entries use OR logic",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto", "DeprecatedUser"),
				typing.Named("example.com/project/internal/dto/auth/internal", "InternalToken"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							ExcludeModels: []ModelFilter{
								{Name: "^Deprecated"},
								{Path: "^auth/internal$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.User",
				"example.com/project/internal/dto/auth.LoginRequest",
			},
		},
		{
			name: "type excluded in one root passes through overlapping root without filter",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth", "LoginResponse"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							ExcludeModels: []ModelFilter{
								{Name: "^LoginRequest$"},
							},
						},
						{
							Path:      filepath.Join(root, "internal", "dto", "auth"),
							Recursive: false,
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.User",
				"example.com/project/internal/dto/auth.LoginRequest",
				"example.com/project/internal/dto/auth.LoginResponse",
			},
		},
		{
			name: "include root package only via empty path filter",
			models: []*typing.Type{
				typing.Named("example.com/project/internal/dto", "User"),
				typing.Named("example.com/project/internal/dto/auth", "LoginRequest"),
				typing.Named("example.com/project/internal/dto/auth/internal", "InternalToken"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Path: "^$"},
							},
						},
					},
				},
			},
			want: []string{
				"example.com/project/internal/dto.User",
			},
		},
		{
			name: "unknown packages kept untouched when filter provided",
			models: []*typing.Type{
				typing.Named("github.com/labstack/echo/v4", "Map"),
			},
			cfg: Config{
				Input: InputConfig{
					Models: []ModelsConfig{
						{
							Path:      filepath.Join(root, "internal", "dto"),
							Recursive: true,
							IncludeModels: []ModelFilter{
								{Path: "^test$"},
							},
						},
					},
				},
			},
			want: []string{
				"github.com/labstack/echo/v4.Map",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			g, err := New(tt.cfg)
			require.NoError(t, err, "create generator")

			got, err := g.filterModels(tt.models)
			require.NoError(t, err)

			gotNames := modelKeys(got)
			require.ElementsMatch(t, tt.want, gotNames)
		})
	}
}

func modelKeys(models []*typing.Type) []string {
	out := make([]string, 0, len(models))
	for _, m := range models {
		out = append(out, m.Pkg()+"."+m.Name())
	}
	sort.Strings(out)
	return out
}
