// Code generated by typed. DO NOT EDIT
package openapi

import (
	dto "examples/dto"

	typed "github.com/d1vbyz3r0/typed"
	typing "github.com/d1vbyz3r0/typed/common/typing"
	openapi3 "github.com/getkin/kin-openapi/openapi3"
	v4 "github.com/labstack/echo/v4"
)

var registry = typed.MustNewRegistry(
	typed.T{Val: new(dto.Form), ImportAlias: "dto", Type: typing.Named("examples/dto", "Form")},
	typed.T{Val: new(dto.FormUploadResp), ImportAlias: "dto", Type: typing.Named("examples/dto", "FormUploadResp")},
	typed.T{Val: new(dto.Status), ImportAlias: "dto", Type: typing.Enum(typing.Named("examples/dto", "Status"), []any{"active", "inactive"})},
	typed.T{Val: new(dto.User), ImportAlias: "dto", Type: typing.Named("examples/dto", "User")},
	typed.T{Val: new(v4.Map), ImportAlias: "v4", Type: typing.Named("github.com/labstack/echo/v4", "Map")},
	typed.T{Val: new(string), Type: typing.Basic("string")},
)

var spec = &openapi3.T{
	OpenAPI: "3.0.0",
	Info: &openapi3.Info{
		Title:   "Example api",
		Version: "0.0.1",
	},
	Servers: []*openapi3.Server{
		{
			URL: "http://localhost:8080",
		},
	},
}
